### ISSUE TITLE
Wrong screen rotation

### ISSUE THREAD

**Issue by douglas-laidlaw** [AOtools/soapy#99] opened 2018-12-23 19:45 UTC
Wind directions of 90 and 270 are flipped. This is an easy fix. See ~ln.520 within atmosphere.py. When  using e.g. 91 and 271, wind direction is correct (the problem is when using exactly 90 and 270).

**Comment by matthewtownson** [comment] 2020-03-02 20:04
Duplicate of #83

**Closed by matthewtownson** 2020-03-02 20:04 UTC
